name: amazon_s3_cognito
description: This plugin allows users to upload and delete image for amazon s3 cognito
version: 0.3.0

homepage: https://github.com/prachiFam/amazon_s3_cognito

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.famproperties.amazon_s3_cognito
    pluginClass: AmazonS3CognitoPlugin
